name: SteveZaudio
favicon: null
layout_spectrum: 0.25283704069443047
typography_spectrum: 0.53377775545232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9011902494821697
  lightness: 0.4958476896863431
  saturation: 0.14126900606788695
  rhythmicContrast: 0.16004397138021886
purpose: []
